version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.11.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: on-failure:5
    env_file:
      - .env.template
    ports:
      - "15672:15672" # web interface
      - "5672:5672" # AMQP
    volumes:
      - ../runners/rabbitmq:/var/lib/rabbitmq
