version: "3.5"

services:
  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    container_name: minio
    hostname: minio
    restart: on-failure:5
    command: server --console-address ":9001" ../runners/minio
    env_file:
      - .env.template
    ports:
      - "9000:9000"
      - "9001:9001" # web interface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ../runners/minio:/data

  minio-mc:
    image: minio/mc:RELEASE.2023-02-28T00-12-59Z
    container_name: minio-mc
    depends_on:
      - minio
    env_file:
      - .env.template
    volumes:
      - ./create_bucket.sh:/create_bucket.sh
    entrypoint: "bash /create_bucket.sh"
